     		<div id="count">
	            <div id="nav">
	                <a href="#">Вернуть</a>&nbsp;|&nbsp;<a href="#">Отменить</a>
	            </div>
	            <span id="groups-hook"></span>
            </div>
<script type="text/javascript">
(function(){
	//bootstrap
	$(function(){
		Views.App.getInstance();
		DataSource.Groups = <?=$this->groups?>;
		DataSource.Categories = <?=$this->categories?>;

		Collections.Groups.getInstance().forEach(function(model){
			var categories = Collections.Categories.getInstance().search({group_id: model.id});
			var group_view  = new Views.Group({model: model});

			for (var i in categories){
				group_view.addCategoryView(new Views.Category({model: categories[i]}));
			}
		});
	});
})();
</script>


<script type="text/template" id="category-row">
<tr>
<td>
	 <span class="tab-menu cat-item" data-field="title">{{title}}</span>
</td>
<td class="tdrg" data-field="amount">{{amount}}</td>
</tr>

</script>

<script type="text/template" id="group-table">
 <table class="count_tb count_tb_ex">
<tr>
	<th>
		<span class="tab-menu group-item" data-field="name">{{name}}</span>
	</th>
	<th>
		Сумма
	</th>
</tr>
<tr id="categories-hook">
	<td colspan="2" class="tdbg"></td>
</tr>
</table>
</script>

<script type="text/template" id="cm-cats">
	<div class="info-menu">
		<a href="#" action="edit-category">Редактировать</a>
		<br/>
		<a href="#" action="delete-category" >Удалить</a>
	</div>
</script>
<script type="text/template" id="cm-groups">
	<div class="info-menu">
		<a href="#" action="add-category">Добавить категорию</a>
		<br/>
 		<a href="#">Редактировать</a>
		<br/>
		<a href="#">Удалить</a>
	</div>
</script>

<script id="confirmation-dialog" type="text/template">
<div class="form form-t">
{{text}}
</div>
</script>

<script id="category-dialog" type="text/template">
<div class="form" id="dialog-content">
<table>
	<tr>
		<td>
			Название:*
		</td>
		<td>
			<input type="text" name="title" data-submit="allowed" />
		</td>
	</tr>
	<tr>
		<td>
			Сумма:
		</td>
		<td>
			<input type="text" name="amount" data-submit="allowed" />
		</td>
	</tr>
	<tr>
		<td>
			Группа:
		</td>
		<td><select id="groups-select" name="group_id" data-submit="allowed"></select>
		</td>
	</tr>
	<tr>
		<td>
			Прикрепить:
		</td>
		<td>
			<input type="checkbox" name="pin" value="1" data-submit="allowed" />
		</td>
	</tr>
</table>
</div>
</script>

<script type="text/template" id="dialog-layout">
<div class="dlg-cont">
<div class="bg"></div>
<div class="cont">
<div class="dlg">
<div class="dlg-head">
     <span class="dlg-title">{{title}}</span>
     <a href="#" class="dlg-close"></a>
</div>
<div class="dlg-c">
		<div id="dialog-content">
		</div>
		<div id="butt">
			<button class="form submit-button">{{submit}}</button>&nbsp;&nbsp;
    		<button class="form cancel-button">{{cancel}}</button>
		</div>
     <br class="clr"/>
</div>
</div>
</div>
</div>
</script>