<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?=$this->title?></title>
        <link rel="stylesheet" href="/front/css/main.css" />
        <script type="text/javascript" src="/front/js/jquery-1.8.2.min.js"></script>
		<script type="text/javascript" src="/front/js/underscore-min.js"></script>
		<script type="text/javascript" src="/front/js/backbone-min.js"></script>
		<script type="text/javascript" src="/front/js/handlebars.js"></script>
		<script type="text/javascript" src="/front/js/app.js"></script>
    </head>
    <body>
        <div id="tp">

        </div>
        <div id="content">
           		<span id="header-hook"></span>
           		<script>
           			//bootstrap
					$(function(){
						new Views.Budget({model: new Models.Budget(<?=$this->budget?>)});
					});
           		</script>
	           	 <div id="left">
	                <ul>
	                    <li <?=is_location('/operations/flow/index') ? 'class="select"' : '' ?>>
	                        <a href="/operations/flow/index">Флоу</a>
	                    </li>
	                    <li <?=is_location('/operations/planner/index') ? 'class="select"' : '' ?>>
	                        <a href="/operations/planner/index">Планнер</a>
	                    </li>
	                    <li <?=is_location('/history/index/index') ? 'class="select"' : '' ?>>
	                        <a href="#">История операций</a>
	                    </li>
	                    <li <?=is_location('/archive/planner/index') ? 'class="select"' : '' ?>>
	                        <a href="#">Архив</a>
	                    </li>
	                </ul>

	                <?php if (is_location('/operations/planner/index')):?>
	                <div id="new-gr">
                    	<a href="#"><b>Добавить группу</b></a>
                	</div>
                	<?php endif;?>
	            </div>
	            <div id="right">
	            	<div id="count">
						<div id="nav">
							<a href="#">Вернуть</a>&nbsp;|&nbsp;<a href="#">Отменить</a>
						</div>
	            		<?=$this->_getView();?>
	            	</div>
	            </div>
            <div id="footer">
                Kisya &amp; Solnyshko Co. All rights reserved. 2012
            </div>
        </div>

<script type="text/template" id="tmp-main-header">
	 <div id="header-top">
		<div id="tp-left">
			Остаток: {{remainder}}
		</div>
		<div id="tp-right">
			<b>Бюджет:</b> {{budget}} &nbsp;&nbsp;
			<b>Расходы:</b> {{expenses}}
		</div>
		<br class="clr" />
	 </div>

	 <div id="header">
		 <div id="hd-left">Манипулятор</div>
		 <div id="menu">
				 <a href="#">Внести сумму</a>
				 <a href="#">Забрать сумму</a>
				 <a href="#" id="last">Новый месяц</a>
		  </div>
		<br class="clr" />
	 </div>
</script>
    </body>
</html>