<span id="groups-hook"></span>
<script type="text/javascript">
//bootstrap
(function(){
	$(function(){
		Views.App.getInstance();
		DataSource.Groups = <?=$this->groups?>;
		DataSource.Categories = <?=$this->categories?>;

		Collections.Groups.getInstance().forEach(function(model){
			var categories = Collections.Categories.getInstance().search({group_id: model.id});
			var group_view  = new Views.PseudoGroup({model: model});

			for (var i in categories){
				new Views.PseudoCategory({model: categories[i]}).render(group_view);
			}
		});
	});
})();

</script>


<script type="text/template" id="category-row">
<tr>
<td>
	 <span class="tab-menu cat-item" data-field="title">{{title}}</span>
</td>
<td class="tdrg" data-field="current_amount">{{current_amount}}</td>
</tr>
</script>

<script type="text/template" id="group-table">
 <table class="count_tb count_tb_ex">
<tr>
	<th>
		<span class="group-item" data-field="name">{{name}}</span>
	</th>
	<th>
		Сумма
	</th>
</tr>
<tr id="categories-hook">
	<td colspan="2" class="tdbg"></td>
</tr>
</table>
</script>

<script type="text/template" id="cm-cats">
	<div class="info-menu">
		<a href="#" action="withdrawal">Снять сумму</a>
		<br/>
		<a href="#" action="return-amount">Сделать возврат</a>
	</div>
</script>

<script id="withdrawal-dialog" type="text/template">
<div class="form">
	<table>
		<tr>
			<td>
				Сумма:
			</td>
			<td>
				<input type="text" name="amount" data-submit="allowed" />
			</td>
		</tr>
	</table>
	</div>
</script>