<script type="text/javascript">

(function(){
	$(function(){
		Views.App.getInstance();
		DataSource.Groups = <?=$this->groups?>;
		DataSource.Categories = <?=$this->categories?>;
	});
})();

</script>
<table class="count_tb count_tb_ex">
	<tr>
		<th>
			<span class="tab-menu">Описание</span>
		</th>
		<th>
			Сумма
		</th>
	</tr>
	<tr>
		<td>
			 <span class="tab-menu">Кисина поездка к родным
				 <div class="info-menu">
					 <a href="#"><b>Забрать сумму</b></a>
					 <a href="#"><b>Сбалансировать</b></a>
				 </div>
			 </span>
		</td>
		<td class="tdrg">
			6
		</td>
	</tr>
	<tr>
		<td>
			 <span class="tab-menu">Кисин обед</span>
		</td>
		<td class="tdrg">
			200
		</td>
	</tr>
	<tr>
		<td>
			 <span class="tab-menu">Поезка на работу</span>
		</td>
		<td class="tdrg">
			400
		</td>
	</tr>
	<tr>
		<td>
			 <span class="tab-menu">Киичкина прическа</span>
		</td>
		<td class="tdrg">
		   1000
		</td>
	</tr>
	<tr>
		<td colspan="2" class="tdbg"> </td>
	</tr>
</table>

<table class="count_tb count_tb_ex">
	<tr>
		<th>
			<span class="tab-menu">Описание</span>
		</th>
		<th>
			Сумма
		</th>
	</tr>
	<tr>
		<td>
			 <span class="tab-menu">Солнышкина поезка в село
			  </span>
		</td>
		<td class="tdrg">
			200
		</td>
	</tr>
	<tr>
		<td>
			 <span class="tab-menu">Солнышкин обед</span>
		</td>
		<td class="tdrg">
			200
		</td>
	</tr>
	<tr>
		<td>
			 <span class="tab-menu">Поездка на работу</span>
		</td>
		<td class="tdrg">
			120
		</td>
	</tr>
	<tr>
		<td>
			 <span class="tab-menu">Солнышкина прическа</span>
		</td>
		<td class="tdrg">
		   45
		</td>
	</tr>
	<tr>
		<td colspan="2" class="tdbg"> </td>
	</tr>
</table>