 <script>
 test('Lib.Url', function() {
 	var url = new Lib.Url('?key1=1&key2=2');
  	url.set('key3', 3);
	url.unset('key1');
	ok(url.toString() == 'key2=2&key3=3', 'Normal use');

	var url = new Lib.Url('sdf @sdf sd');
	ok(url.toString() == '', 'Wrong format use');

	var url = new Lib.Url(' ');
	ok(url.toString() == '', 'Empty use');

	var url = new Lib.Url();
	url.set('key', 'тестинг хороший должен быть');
	ok(url.toString() == 'key=' + encodeURIComponent('тестинг хороший должен быть'), 'UTF and spaces use');

	var url = new Lib.Url('?key=' + encodeURIComponent('тестинг хороший должен быть'));
	ok(url.get('key') == 'тестинг хороший должен быть', '(vise versa) UTF and spaces use');

	var url = new Lib.Url('sdf @sdf sd');
	url.set('key', 1);
	ok(url.toString() == 'key=1', 'Wrong format and one key use');

	var url = new Lib.Url('?key1=1&key2=2');
	var key3 = url.get('key3');
	ok(typeof key3 === 'undefined', 'Test undefined key');

 });
 </script>