
var Helpers={Abstract:{},Interface:{}};var Views={Abstract:{},Interface:{}};var Collections={Abstract:{},Interface:{}};var Models={Abstract:{},Interface:{}};var Lib={Abstract:{},Interface:{}};var Resources={};var DataSource={};
Resources={group:'/operations/planner/{method}-group',category:'/operations/planner/{method}-category'};
String.prototype.toCamelCase=function(){var arr=this.split('-');var n_str='';for(var i in arr){n_str+=arr[i].charAt(0).toUpperCase()+arr[i].substr(1);}
return n_str.charAt(0).toLowerCase()+n_str.substr(1);}
function pred(data){alert(JSON.stringify(data));}
Backbone.sync=function(method,model,options){var url=_.isFunction(model.url)?model.url():model.url;var method_map={'create':'POST','update':'POST','delete':'POST','read':'GET'};if(!_.has(method_map,method)){return false;}
url=url.replace('{method}',method);var settings={type:method_map[method],url:url,data:model.toJSON(),dataType:'json',success:_.isFunction(options.success)?options.success:function(){},error:function(data){if(data.status=='403'){var jdata;try{jdata=$.parseJSON(data.responseText);}catch(e){throw'Response error: '+data.responseText+' : '+data.status;}
if(_.isFunction(options.error)){options.error(new Lib.ErrorHandler(jdata));return;}}
throw'Response error: '+data.responseText+' : '+data.status;}}
return $.ajax(settings);};$.fn.dataForSubmit=function(){var data={};this.find('[data-submit]').each(function(e){var $this=$(this);var $val=$this.val();if(($this.attr('type')=='checkbox'||$this.attr('type')=='radio')&&!$this.attr('checked')){$val=0;}
data[$this.attr('name')]=$val;});return data;};$.fn.refreshDataFields=function(data){for(var i in data){this.find('[data-field="'+i+'"]').html(_.escape(data[i]));}
return data;};
(function(){var initializing=false,fnTest=/xyz/.test(function(){xyz;})?/\b_super\b/:/.*/;this.Class=function(){};Class.extend=function(prop){var _super=this.prototype;initializing=true;var prototype=new this();initializing=false;for(var name in prop){prototype[name]=typeof prop[name]=="function"&&typeof _super[name]=="function"&&fnTest.test(prop[name])?(function(name,fn){return function(){var tmp=this._super;this._super=_super[name];var ret=fn.apply(this,arguments);this._super=tmp;return ret;};})(name,prop[name]):prop[name];}
function Class(){if(!initializing&&this.initialize)
this.initialize.apply(this,arguments);}
Class.prototype=prototype;Class.prototype.constructor=Class;Class.extend=arguments.callee;return Class;};})();
Lib.Eventor=Class.extend(Backbone.Events);Lib.Eventor._INSTANCE=null;Lib.Eventor.getInstance=function(){if(Lib.Eventor._INSTANCE==null){Lib.Eventor._INSTANCE=new Lib.Eventor();}
return Lib.Eventor._INSTANCE;};
Lib.Collection=Class.extend({_data:null,initialize:function(){this._data={};},add:function(key,value){var data={};data[key]=value;$.extend(this._data,data);return this;},get:function(key){return this._data[key];}});
Lib.ErrorHandler=Class.extend({_error_data:null,initialize:function(data){this._error_data=data;},display:function(){var message='';var n='';for(var i in this._error_data){message+=n+this._error_data[i];n="\n";}
alert(message);}});
Lib.Register={_data:{},add:function(key,value){var data={};data[key]=value;$.extend(this._data,data);},get:function(key){return this._data[key];}};
Lib.RemoteRun={_channels:new Lib.Collection(),execute:function(channel,func,params){var context=this._channels.get(channel);if(_.isFunction(func)){func.apply(context,_.isUndefined(params)?[]:params);}},access:function(channel,context){this._channels.add(channel,context);}};
Collections.Abstract.Collection=Backbone.Collection.extend({search:function(data){var res=this.where(data);var _return=[];if(res.length==0){return _return;}
for(var i in res){_return.push(this.get(res[i].id));}
return _return;},searchOne:function(data){var res=this.search(data);if(res.length==0){return res;}
return res.shift();}});
Models.Abstract.Model=Backbone.Model.extend({});
Models.Group=Models.Abstract.Model.extend({urlRoot:Resources.group});
Models.Category=Models.Abstract.Model.extend({urlRoot:Resources.category});
Collections.Groups=Collections.Abstract.Collection.extend({model:Models.Group});Collections.Groups._INSTANCE=null;Collections.Groups.getInstance=function(){if(Collections.Groups._INSTANCE==null){Collections.Groups._INSTANCE=new Collections.Groups(DataSource.Groups);}
return Collections.Groups._INSTANCE;}
Collections.Categories=Collections.Abstract.Collection.extend({model:Models.Category});Collections.Categories._INSTANCE=null;Collections.Categories.getInstance=function(){if(Collections.Categories._INSTANCE==null){Collections.Categories._INSTANCE=new Collections.Categories(DataSource.Categories);}
return Collections.Categories._INSTANCE;}
Views.Abstract.View=Backbone.View.extend({_models:null,initialize:function(){this._models=new Lib.Collection();},addModel:function(key,model){this._models.add(key,model);return this;},getModel:function(key){return this._models.get(key);},getDom:function(){return this.$el;}});
$(function(){Views.Abstract.ContextMenu=Views.Abstract.View.extend({_is_shown:false,_coor:{},_context_menu_helper:null,_context:null,events:{'click a':function(e){this._context_menu_helper.doAction(e);this.hide();return false;}},initialize:function(){Views.Abstract.View.prototype.initialize.apply(this,arguments);this.render();this.$el.mousedown(function(){return false;});Lib.Eventor.getInstance().on('click:body',function(){if(this.isShown()){this.hide();}},this);},render:function(){this.$el=$(this._template.html());$('body').append(this.$el);},show:function(coor){this._coor=coor;this.$el.show();this._setPosition();this._is_shown=true;},hide:function(){this.$el.hide();this._is_shown=false;},isShown:function(){return this._is_shown;},setContext:function(context){this._context=context;return this;},getContext:function(){return this._context;},_setPosition:function(){this.$el.css({left:this._coor.x,top:this._coor.y});}});});
$(function(){Views.Abstract.Dialogs=Views.Abstract.View.extend({_template:null,_is_shown:false,_dialog_helper:null,_layout:$("#dialog-layout"),_layout_data:{'title':'Диалоговое окно','submit':'Применить','cancel':'Отмена'},events:{'click .cancel-button, .dlg-close':function(){this._dialog_helper.doCancel();return false;},'click .submit-button':function(){this._dialog_helper.doSubmit();}},initialize:function(){Views.Abstract.View.prototype.initialize.apply(this,arguments);this.render();},render:function(){var content_template=Handlebars.compile(this._template.html());var layout_template=Handlebars.compile(this._layout.html());var layout_data={};$.extend(layout_data,this._layout_data,this._getLayoutData());this.$el=$(layout_template(layout_data));this.$el.find('#dialog-content').html(content_template(this._getContentData()));$('body').append(this.$el);},_getContentData:function(){return{};},_getLayoutData:function(){return{}},_update:function(){},show:function(){this._update();this.$el.show();this._adjustWindow();this._is_shown=true;},hide:function(){this.$el.hide();this._is_shown=false;},isShown:function(){return this._is_shown;},disableUI:function(){this.$el.find('.submit-button').attr('disabled','disabled');return this;},enableUI:function(){this.$el.find('.submit-button').removeAttr('disabled');return this;},_adjustWindow:function(){var $dlg=this.$el.find('.dlg');var top=Math.round($dlg.height()/2);$dlg.css('margin-top','-'+top+'px');}});});
$(function(){Views.App=Views.Abstract.View.extend({el:'html',events:{'mousedown body':function(){Lib.Eventor.getInstance().trigger('click:body')}}});Views.App._INSTANCE=null;Views.App.getInstance=function(){if(Views.App._INSTANCE==null){Views.App._INSTANCE=new Views.App();}
return Views.App._INSTANCE;}});
$(function(){Views.CategoryContextMenu=Views.Abstract.ContextMenu.extend({_template:$('#cm-cats'),initialize:function(){Views.Abstract.ContextMenu.prototype.initialize.apply(this,arguments);this._context_menu_helper=new Helpers.CategoryContextMenu(this);}});Views.CategoryContextMenu._INSTANCE=null;Views.CategoryContextMenu.getInstance=function(){if(Views.CategoryContextMenu._INSTANCE==null){Views.CategoryContextMenu._INSTANCE=new Views.CategoryContextMenu();}
return Views.CategoryContextMenu._INSTANCE;}});
$(function(){Views.GroupContextMenu=Views.Abstract.ContextMenu.extend({_template:$('#cm-groups'),initialize:function(){Views.Abstract.ContextMenu.prototype.initialize.apply(this,arguments);this._context_menu_helper=new Helpers.GroupContextMenu(this);}});Views.GroupContextMenu._INSTANCE=null;Views.GroupContextMenu.getInstance=function(){if(Views.GroupContextMenu._INSTANCE==null){Views.GroupContextMenu._INSTANCE=new Views.GroupContextMenu();}
return Views.GroupContextMenu._INSTANCE;}});
$(function(){Views.Group=Views.Abstract.View.extend({_template:$('#group-table'),events:{'click .group-item':function(e){Views.GroupContextMenu.getInstance().setContext(this).show({x:e.pageX,y:e.pageY});return false;}},initialize:function(){Views.Abstract.View.prototype.initialize.apply(this,arguments);Collections.Categories.getInstance().on('add',$.proxy(function(model){if(model.get('group_id')==this.model.id){new Views.Category({model:model}).render(this);}},this));this.render();Lib.Register.get('group_views').add('group_'+this.model.id,this);this.model.on('change',$.proxy(function(){this.refresh();},this));this.model.on('destroy',$.proxy(function(){this.remove();},this));},render:function(){var template=Handlebars.compile(this._template.html());this.$el=$(template(this.model.toJSON()));this.$el.insertBefore('#groups-hook');this.delegateEvents();return this;},refresh:function(){this.$el.refreshDataFields(this.model.toJSON());return this;}});});
$(function(){Views.Category=Views.Abstract.View.extend({_template:$('#category-row'),events:{'click .cat-item':function(e){Views.CategoryContextMenu.getInstance().setContext(this).show({x:e.pageX,y:e.pageY});return false;}},initialize:function(){Views.Abstract.View.prototype.initialize.apply(this,arguments);this.model.on('change',$.proxy(function(){this.refresh();},this));this.model.on('change:group_id',$.proxy(function(model){this._reRender(Lib.Register.get('group_views').get('group_'+model.get('group_id')));},this));this.model.on('destroy',$.proxy(function(){this.remove();},this));},render:function(parent){var template=Handlebars.compile(this._template.html());this.setElement($(template(this.model.toJSON())));this.$el.insertBefore(parent.$el.find('#categories-hook'));return this;},_reRender:function(parent){this.remove();this.render(parent);},refresh:function(){this.$el.refreshDataFields(this.model.toJSON());return this;}});});
$(function(){Views.NewCategoryDialog=Views.Abstract.Dialogs.extend({_template:$('#category-dialog'),initialize:function(){Views.Abstract.Dialogs.prototype.initialize.apply(this,arguments);this._dialog_helper=new Helpers.NewCategoryDialog(this);},_getLayoutData:function(){return{title:'Создать новую категорию'};},_update:function(){Views.Abstract.Dialogs.prototype._update.apply(this,arguments);var options='';var groups=Collections.Groups.getInstance().toJSON();for(var i in groups){options+='<option value=\''+groups[i].id+'\'>'+groups[i].name+'</option>';}
this.$el.find('#groups-select').html(options);this.$el.find('[name=title], [name=amount]').val('');this.$el.find('[name=pin]').removeAttr('checked');this.$el.find('[name=group_id]').val(this.getModel('group').id);}});Views.NewCategoryDialog._INSTANCE=null;Views.NewCategoryDialog.getInstance=function(){if(Views.NewCategoryDialog._INSTANCE==null){Views.NewCategoryDialog._INSTANCE=new Views.NewCategoryDialog();}
return Views.NewCategoryDialog._INSTANCE;}});
$(function(){Views.EditCategoryDialog=Views.Abstract.Dialogs.extend({_template:$('#category-dialog'),initialize:function(){Views.Abstract.Dialogs.prototype.initialize.apply(this,arguments);this._dialog_helper=new Helpers.EditCategoryDialog(this);},_getLayoutData:function(){return{title:'Редактировать категорию'};},_update:function(){Views.Abstract.Dialogs.prototype._update.apply(this,arguments);var options='';var groups=Collections.Groups.getInstance().toJSON();for(var i in groups){options+='<option value=\''+groups[i].id+'\'>'+groups[i].name+'</option>';}
this.$el.find('#groups-select').html(options);this.$el.find('[name=title]').val(this.getModel('category').get('title'));this.$el.find('[name=amount]').val(this.getModel('category').get('amount'));this.$el.find('[name=pin]').removeAttr('checked');if(this.getModel('category').get('pin')>0){this.$el.find('[name=pin]').attr('checked','checked');}
this.$el.find('[name=group_id]').val(this.getModel('category').get('group_id'));}});Views.EditCategoryDialog._INSTANCE=null;Views.EditCategoryDialog.getInstance=function(){if(Views.EditCategoryDialog._INSTANCE==null){Views.EditCategoryDialog._INSTANCE=new Views.EditCategoryDialog();}
return Views.EditCategoryDialog._INSTANCE;}});
$(function(){Views.Confirmation=Views.Abstract.Dialogs.extend({_text:'',_template:$('#confirmation-dialog'),initialize:function(text,helper){this._text=text;Views.Abstract.Dialogs.prototype.initialize.apply(this,arguments);this._dialog_helper=new helper(this);},_getLayoutData:function(){return{title:'Внимание!',submit:'Да',cancel:'Нет'};},_getContentData:function(){return{text:this._text};}});});
$(function(){Views.NewGroupLink=Views.Abstract.View.extend({el:$('#new-gr'),events:{'click a':function(){Views.NewGroupDialog.getInstance().show();return false;}}});});
$(function(){Views.NewGroupDialog=Views.Abstract.Dialogs.extend({_template:$('#group-dialog'),initialize:function(){Views.Abstract.Dialogs.prototype.initialize.apply(this,arguments);this._dialog_helper=new Helpers.NewGroupDialog(this);},_getLayoutData:function(){return{title:'Создать новую группу'};},_update:function(){Views.Abstract.Dialogs.prototype._update.apply(this,arguments);this.$el.find('[name=name]').val('');}});Views.NewGroupDialog._INSTANCE=null;Views.NewGroupDialog.getInstance=function(){if(Views.NewGroupDialog._INSTANCE==null){Views.NewGroupDialog._INSTANCE=new Views.NewGroupDialog();}
return Views.NewGroupDialog._INSTANCE;}});
$(function(){Views.EditGroupDialog=Views.Abstract.Dialogs.extend({_template:$('#group-dialog'),initialize:function(){Views.Abstract.Dialogs.prototype.initialize.apply(this,arguments);this._dialog_helper=new Helpers.EditGroupDialog(this);},_getLayoutData:function(){return{title:'Редактировать группу'};},_update:function(){Views.Abstract.Dialogs.prototype._update.apply(this,arguments);this.$el.find('[name=name]').val(_.escape(this.getModel('group').get('name')));}});Views.EditGroupDialog._INSTANCE=null;Views.EditGroupDialog.getInstance=function(){if(Views.EditGroupDialog._INSTANCE==null){Views.EditGroupDialog._INSTANCE=new Views.EditGroupDialog();}
return Views.EditGroupDialog._INSTANCE;}});
Helpers.Abstract.Helper=Class.extend({_view:null,initialize:function(view){this._view=view;}});
Helpers.Abstract.ContextMenu=Helpers.Abstract.Helper.extend({doAction:function(e){var action=$(e.target).attr('action');if(!_.isString(action)){return;}
var method=action.toCamelCase();if(!_.isFunction(this[method])){return;}
this[method]();}});
$(function(){Helpers.CategoryContextMenu=Helpers.Abstract.ContextMenu.extend({_delete_confirm:null,editCategory:function(){Views.EditCategoryDialog.getInstance().addModel('category',this._view.getContext().model).show();},deleteCategory:function(){if(_.isNull(this._delete_confirm)){var title='Вы уверены что хотите удалить данную категорию?';this._delete_confirm=new Views.Confirmation(title,Helpers.DeleteCategoryConfirmation);}
this._delete_confirm.addModel('category',this._view.getContext().model).show();}});})
$(function(){Helpers.GroupContextMenu=Helpers.Abstract.ContextMenu.extend({_delete_confirmation:null,addCategory:function(){Views.NewCategoryDialog.getInstance().addModel('group',this._view.getContext().model).show();},editGroup:function(){Views.EditGroupDialog.getInstance().addModel('group',this._view.getContext().model).show();},deleteGroup:function(){if(_.isNull(this._delete_confirmation)){var text='Вы уверены, что хотите удалить данную группу?';this._delete_confirmation=new Views.Confirmation(text,Helpers.DeleteGroupConfirmation);}
this._delete_confirmation.addModel('group',this._view.getContext().model).show();}});});
$(function(){Helpers.NewCategoryDialog=Helpers.Abstract.Helper.extend({doCancel:function(){this._view.hide();},doSubmit:function(){var data=this._view.getDom().dataForSubmit();this._view.disableUI();new Models.Category().save(data,{success:$.proxy(function(model,data){Collections.Categories.getInstance().add(model);this._view.enableUI();this._view.hide();},this),error:$.proxy(function(model,error_handler){this._view.enableUI();error_handler.display();},this)});}});});
$(function(){Helpers.EditCategoryDialog=Helpers.Abstract.Helper.extend({doCancel:function(){this._view.hide();},doSubmit:function(){var data=this._view.getDom().dataForSubmit();this._view.disableUI();this._view.getModel('category').save(data,{wait:true,success:$.proxy(function(model,data){this._view.enableUI();this._view.hide();},this),error:$.proxy(function(model,error_handler){this._view.enableUI();error_handler.display();},this)});}});});
Helpers.DeleteCategoryConfirmation=Helpers.Abstract.Helper.extend({doCancel:function(){this._view.hide();},doSubmit:function(){this._view.disableUI();this._view.getModel('category').destroy({wait:true,success:$.proxy(function(model,data){this._view.enableUI();this._view.hide();},this),error:$.proxy(function(model,error_handler){this._view.enableUI();this._view.hide();error_handler.display();},this)});this._view.hide();}});
Helpers.NewGroupDialog=Helpers.Abstract.Helper.extend({doCancel:function(){this._view.hide();},doSubmit:function(){var data=this._view.getDom().dataForSubmit();this._view.disableUI();new Models.Group().save(data,{success:$.proxy(function(model){Collections.Groups.getInstance().add(model);new Views.Group({model:model});this._view.enableUI();this._view.hide();},this),error:$.proxy(function(model,error_handler){this._view.enableUI();error_handler.display();},this)});}});
Helpers.EditGroupDialog=Helpers.Abstract.Helper.extend({doCancel:function(){this._view.hide();},doSubmit:function(){var data=this._view.getDom().dataForSubmit();this._view.disableUI();this._view.getModel('group').save(data,{wait:true,success:$.proxy(function(model){this._view.enableUI();this._view.hide();},this),error:$.proxy(function(model,error_handler){this._view.enableUI();error_handler.display();},this)});}});
Helpers.DeleteGroupConfirmation=Helpers.Abstract.Helper.extend({doCancel:function(){this._view.hide();},doSubmit:function(){this._view.disableUI();this._view.getModel('group').destroy({wait:true,success:$.proxy(function(model,data){this._view.enableUI();this._view.hide();},this),error:$.proxy(function(model,error_handler){this._view.enableUI();this._view.hide();error_handler.display();},this)});this._view.hide();}});