
<div id="search-bl">
	<div id="search-arcv-inf">
	 <table class="mf-7">
			<tr>
				<td>
					С:
				</td>
				<td>
				  <input type="text" name="date_from" />
				</td>
				<td rowspan="2" />
					<input type="submit" value="Найти" name="by_date" />
				</td>
			</tr>
			<tr>
				<td>
					По:
				</td>
				<td class="mf-8">
				   <input type="text" name="date_to" />
				</td>
			</tr>
		</table>
	</div>
	<div id="token-hist">
		<table class="mf-1 mf-7">
			<tr>
				<td>
					Ключевое<br/>слово:
				</td>
				<td>
					<input type="text" class="mf-6" name="keyword" />
				</td>
				<td class="mf-8">
					<input type="submit" value="Найти" name="by_keyword" />
				</td>
			</tr>
		</table>
	</div>
	<br class="clr" />
</div>
 <div id="info-hist">
 	<table class="count_tb">
		<tr id="log-hook">
			<th class="mf-4">
				Дата
			</th>
			<th>
				Бюджет / Категория
			</th>
			<th class="mf-5">
				Комментарий
			</th>
			<th class="mf-4">
				Операция
			</th>
			 <th class="sum mf-4">
				Задействованная сумма
			</th>
		</tr>
		<tr>
			<td colspan="5" class="tdbg"> </td>
		</tr>
	</table>
</div>

<script type="text/javascript">
	//bootstrap
	DataSource.Logs = <?=$this->logs?>

	$(function(){

		new Routers.Logs();

		Collections.Logs.getInstance().forEach(function(model){
			new Views.Log({model: model});
		});

		new Views.Search();

		Backbone.history.start();
	});

</script>

<script type="text/template" id="log-row">
	<tr>
			<td>
			  {{insert_date}}
			</td>
			<td>
<span class="tab-menu" data-id="{{id}}">{{item_name}}</span>
			</td>
			<td>
{{comments}}
			</td>
			<td>
{{operation}}
			</td>
			<td class="mf-2">
				{{amount}}
			</td>
		</tr>
</script>