
<div id="search-bl">
	<div id="search-arcv-inf">
	 <table>
			<tr>
				<td>
					С:
				</td>
				<td class="form-text">
				  <input type="text" />
				</td>
				<td rowspan="2" class="form-text">
					<input type="submit" value="Найти">
				</td>
			</tr>
			<tr>
				<td>
					По:
				</td>
				<td class="form-text">
				   <input type="text" />
				</td>
			</tr>
		</table>
	</div>
	<div id="token-hist">
		<table class="mf-1">
			<tr>
				<td class="wrap">
					Бюджет /<br/> Категория:
				</td>
				<td>
					<input type="text"/>
				</td>
				<td>
					<input type="submit" value="Найти">
				</td>
			</tr>
		</table>
	</div>
	<br class="clr"/>
</div>
 <div id="info-hist">
 	<table class="count_tb">
		<tr id="log-hook">
			<th class="mf-4">
				Дата
			</th>
			<th>
				Бюджет / Категория
			</th>
			<th class="mf-5">
				Комментарий
			</th>
			<th class="mf-4">
				Операция
			</th>
			 <th class="sum mf-4">
				Задействованная сумма
			</th>
		</tr>
		<tr>
			<td colspan="5" class="tdbg"> </td>
		</tr>
	</table>
</div>

<script type="text/javascript">
	//bootstrap
	DataSource.Logs = <?=$this->logs?>

	$(function(){
		Collections.Logs.getInstance().forEach(function(model){
			new Views.Log({model: model});
		});
	});

</script>

<script type="text/template" id="log-row">
	<tr>
			<td>
			  {{insert_date}}
			</td>
			<td>
<span class="tab-menu" data-id="{{id}}">{{item_name}}</span>
			</td>
			<td>
{{comments}}
			</td>
			<td>
{{operation}}
			</td>
			<td class="mf-2">
				{{amount}}
			</td>
		</tr>
</script>