<div id="search-bl">
	<div id="search-arcv-inf">
	<form>
	  <table>
			<tr>
				<td>
					С:
				</td>
				<td class="form-text">
				  <input type="text" />
				</td>
				<td rowspan="2" class="form-text">
					<input type="submit" value="Обновить">
				</td>
			</tr>
			<tr>
				<td>
					По:
				</td>
				<td class="form-text">
				   <input type="text" />
				</td>
			</tr>
		</table>
	</form>
	</div>
	<div id="token-hist">
		<table class="mf-1">
			<tr>
				<td class="wrap">
					Найти:
				</td>
				<td>
					<input type="text"/>
				</td>
				<td>
					<input type="submit" value="Обновить">
				</td>
			</tr>
		</table>
	</div>
	<br class="clr"/>
</div>
 <div id="info-hist">
 	<table class="count_tb mf-5">
		<tr>
			<th class="date-sz">
				Дата
			</th>
			<th>
				Бюджет / Категория
			</th>
			<th>
				Комментарий
			</th>
			<th class="operat-sz">
				Операция
			</th>
			 <th class="sum">
				Задействованная сумма
			</th>
		</tr>
		<tr>
			<td>
			   19.10.2012
			</td>
			<td>
<span class="tab-menu">Категория ываыв цуаываы ываыва</span>
			</td>
			<td>
sfsdfsd
			</td>
			<td>
Cнятие денег
			</td>
			<td class="mf-2">
				6.00
			</td>
		</tr>
		<tr>
			<td colspan="5" class="tdbg"> </td>
		</tr>
	</table>
</div>