                <div id="count">
                    <div id="nav">
                <a href="#">Вернуть</a>&nbsp;|&nbsp;<a href="#">Отменить</a>
            </div>
            <?php for($i=0; $i < 5; $i++):?>
                <table class="count_tb count_tb_ex">
                    <tr>
                        <th>
                            <span class="tab-menu group-item">Описание</span>
                        </th>
                        <th>
                            Сумма
                        </th>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu cat-item">Кисина поездка к родным</span>
                        </td>
                        <td class="tdrg">
                            6
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu cat-item">Кисин обед</span>
                        </td>
                        <td class="tdrg">
                            200
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu cat-item">Поезка на работу</span>
                        </td>
                        <td class="tdrg">
                            400
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu cat-item">Киичкина прическа</span>
                        </td>
                        <td class="tdrg">
                           1000
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="tdbg"> </td>
                    </tr>
                </table>
                <?php endfor;?>
            </div>

<script type="text/template" id="cm-cats">
	<div class="info-menu">
 		<a href="#">Задать сумму</a>
		<br/>
		<a href="#">Прикрепить</a>
		<br/>
		<a href="#">Редактировать</a>
		<br/>
		<a href="#">Удалить</a>
	</div>
</script>
<script type="text/template" id="cm-groups">
	<div class="info-menu">
		<a href="#" action="add-category">Добавить категорию</a>
		<br/>
 		<a href="#">Редактировать</a>
		<br/>
		<a href="#">Удалить</a>
	</div>
</script>

<script type="text/template" id="new-cat-dlg">
<div class="dlg-cont">
<div class="bg"></div>
<div class="cont">
    <div class="dlg">
       <div class="dlg-head">
            <span class="dlg-title">Создать новую категорию</span>
            <a href="#" class="dlg-close"></a>
       </div>
       <div class="dlg-c">
       		<div class="form">
       		<table>
       			<tr>
       				<td>
       					Название:
       				</td>
       				<td>
       					<input type="text"/>
       				</td>
       			</tr>
       			<tr>
       				<td>
       					Сумма:
       				</td>
       				<td>
       					<input type="text"/>
       				</td>
       			</tr>
       			<tr>
       				<td>
       					Группа:
       				</td>
       				<td><select id="groups-select"></select>
       				</td>
       			</tr>
       			<tr>
       				<td>
       					Прикрепить:
       				</td>
       				<td>
       					<input type="checkbox"/>
       				</td>
       			</tr>
       		</table>
       		</div>
       		<div id="butt">
       			<button class="form submit-button">Создать</button>&nbsp;&nbsp;
           		<button class="form cancel-button">Отмена</button>
       		</div>
            <br class="clr"/>
       </div>
    </div>
</div>
</div>
</script>