                <div id="count">
                    <div id="nav">
                <a href="#">Вернуть</a>&nbsp;|&nbsp;<a href="#">Отменить</a>
            </div>
            <?php for($i=0; $i < 5; $i++):?>
                <table class="count_tb">
                    <tr>
                        <th>
                            <span class="tab-menu group-item">Описание</span>
                        </th>
                        <th>
                            Сумма
                        </th>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu cat-item">Кисина поездка к родным</span>
                        </td>
                        <td class="tdrg">
                            6
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu cat-item">Кисин обед</span>
                        </td>
                        <td class="tdrg">
                            200
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu cat-item">Поезка на работу</span>
                        </td>
                        <td class="tdrg">
                            400
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu cat-item">Киичкина прическа</span>
                        </td>
                        <td class="tdrg">
                           1000
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="tdbg"> </td>
                    </tr>
                </table>
                <?php endfor;?>
            </div>

<script type="text/template" id="cm-cats">
	<div class="info-menu">
 		<a href="#"><b>Задать сумму</b></a>
		<br/>
		<a href="#"><b>Прикрепить</b></a>
		<br/>
		<a href="#"><b>Редактировать</b></a>
		<br/>
		<a href="#"><b>Удалить</b></a>
	</div>
</script>
<script type="text/template" id="cm-groups">
	<div class="info-menu">
		<a href="#"><b>Добавить категорию</b></a>
		<br/>
 		<a href="#"><b>Редактировать</b></a>
		<br/>
		<a href="#"><b>Удалить</b></a>
	</div>
</script>