<!DOCTYPE html>
<html>
<head>
  	<meta charset="utf-8">
  	<title>QUnit Test</title>
  	<link rel="stylesheet" href="/front/css/qunit.css" />
	<script type="text/javascript" src="/front/js/jquery-1.8.2.min.js"></script>
	<script type="text/javascript" src="/front/js/underscore-min.js"></script>
	<script type="text/javascript" src="/front/js/backbone.js"></script>
	<script type="text/javascript" src="/front/js/handlebars.js"></script>
	<script type="text/javascript" src="/front/js/app.js"></script>
	<script src="/front/js/qunit.js"></script>
</head>
<body>
  <div id="qunit"></div>
  <div id="qunit-fixture"></div>
 <?=$this->_getView();?>
</body>
</html>